export const GETALLMOVIES="GETALLMOVIES";
export const GETPOPULARMOVIE = "GETPOPULARMOVIE";
export const GETRECENTLYMOVIE = "GETRECENTLYMOVIE"
export const FILTERAVERAGE ="FILTERAVERAGE"
export const DETAILMOVIE = "DETAILMOVIE"
export const SEARCHMOVIES = "SEARCHMOVIES"
